### ISSUE TITLE
Ability to accept transmitter-generated audience

### ISSUE THREAD

**Issue by soby** [SGNL-ai/caep.dev#24]
Many implementations have an audience that's dynamically generated by the transmitter after stream creation. The current caep.dev flow requires the audience to be known up front. 

Supporting a transmitter-generated audience would require that caep.dev prefer and use the audience value provided by the transmitter in the stream creation response. 

Alternatively, this can be done manually if the audience is made editable here https://caep.dev/receiver/streams

**Comment by ysarig75** [comment]
+1 for soby's comment. We generate the audience by the transmitter differently for each stream including the stream ID so the audience is not known before the stream creation..

**Comment by kchiranjewee63** [comment]
The issue has been fixed and deployed. The receiver is no longer asking for the audience up front and is now accepting the transmitter-generated audience. I am closing this issue, but feel free to reopen it if anything comes up.
