### ISSUE TITLE
Receiver create stream configuration limit transmitter access token length to 1000

### ISSUE THREAD

**Issue by ysarig75** [SGNL-ai/caep.dev#25]
When trying to configure caep.dev as a receiver to our transmitter, the "create stream" popup is asking for a transmitter access token and there is a limit of a 1000 length limit for the field. Out access tokens are longer (~1400) so I can't create the stream.

Is it possible to increase the limit to 2000 characters?
![Screenshot 2024-10-17 at 10 45 14 AM](https://github.com/user-attachments/assets/476c0aab-ca76-4851-aaf9-5c03b48222a6)

**Comment by kchiranjewee63** [comment]
The issue has been fixed and deployed. I am now closing this issue, but feel free to reopen if anything comes up.
