### ISSUE TITLE
Verification Event should use 'RSA256' but uses 'none'

### ISSUE THREAD

**Issue by thomasdarimont** [SGNL-ai/caep.dev#38]
According to [CAEP Interoperability Profile 1.0 Event Signatures 2.6. ](https://openid.net/specs/openid-caep-interoperability-profile-1_0-ID1.html#section-2.6) all events (including the verification event) should use `RS256 algorithm using a minimum of 2048-bit keys`, however caep.dev uses  `alg: 'none'`at the moment.

**Comment by kchiranjewee63** [comment]
Thank you for reporting this issue.

The issue was due to missed signing of polled events. This has now been fixed and deployed.

I'm closing this issue, but feel free to reopen if anything comes up.

**Comment by thomasdarimont** [comment]
Thanks for the quick turnaround @kchiranjewee63!

Works as expected now: 
<img width="645" alt="image" src="https://github.com/user-attachments/assets/068bbbc3-5702-459f-87eb-5a548c68751a">
