### ISSUE TITLE
`authorization_header` does not appear to be sent back to receiver

### ISSUE THREAD

**Issue by micseltz-cisco** [SGNL-ai/caep.dev#39]
In following the guide for the transmitter, there doesn't appear to be support for the `authorization_header` laid out in the [spec](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html#section-10.3.1.1-6) during setup:

For example the API to setup a stream to `https://ssf.caep.dev/ssf/streams`:
```
{
    "delivery": {
        "authorization_header": "foo",
        "method": "urn:ietf:rfc:8935",
        "endpoint_url": "https://test.com/event"
    },
    "events_requested": [
        "https://schemas.openid.net/secevent/caep/event-type/session-revoked",
        "https://schemas.openid.net/secevent/caep/event-type/credential-change",
        "https://schemas.openid.net/secevent/caep/event-type/device-compliance-change",
        "https://schemas.openid.net/secevent/caep/event-type/token-claims-change",
        "https://schemas.openid.net/secevent/caep/event-type/assurance-level-change"
    ]
}
```

I would expect on my receiver at `https://test.com/event` to have a header:
```
"authorization": "foo"
```

Instead what I see is the following:
```
"headers": {
        "x-amzn-tls-cipher-suite": "TLS_AES_128_GCM_SHA256",
        "content-length": "900",
        "x-amzn-tls-version": "TLSv1.3",
        "x-amzn-trace-id": "****"",
        "x-forwarded-proto": "https",
        "host": "****",
        "x-forwarded-port": "****"",
        "content-type": "application/secevent+jwt",
        "x-forwarded-for": "****"",
        "accept-encoding": "gzip",
        "accept": "application/json",
        "user-agent": "Go-http-client/1.1"
    }
```

**Comment by tulshi** [comment]
Hi, Thanks for bringing this up. A couple of observations:

- The latest implementer's draft spec is [here](https://openid.net/specs/openid-sharedsignals-framework-1_0-ID3.html#name-security-event-token-profil) - it doesn't affect this particular issue, but JFYI
- The use of the authorization header is optional for the push delivery option (RFC8935), and caep.dev sends signed events, so a good way to verify authentic communication is to verify the signature on the received events with the JWKS information in the metadata.

**Comment by micseltz-cisco** [comment]
@tulshi thanks for the quick reply!
We were hoping to have the same url endpoint for all shared signals but if the `authorization_header` is optional it sounds like we'd need to have separate endpoints for each one and use the audience in JWKS to validate. 
Thanks for the info this is helpful and caep.dev is very helpful in getting started with this so thanks for the help here!

I'll close the issue as from what you describe it sounds like this is intentionally not implemented (since the spec doesn't itself require every transmitter to implement forwarding the `authorization_header`). Thanks!

**Comment by tulshi** [comment]
We will add this capability shortly to caep.dev

**Comment by spdaley** [comment]
Hi @tulshi I know you mentioned that it was optional but I just wanted to confirm that, based on the reading of the spec, it's only optional for the receiver to send it right? If the receiver does send it though, the transmitter must use it?

Thanks for looking into adding this capability though, it's greatly appreciated!

**Comment by tulshi** [comment]
Created issue: ["authorization_header" field should be clarified and added to the "Stream Configuration" section (7.1.1)](https://github.com/openid/sharedsignals/issues/223) for spec work.

**Comment by kchiranjewee63** [comment]
CAEP.dev now supports `authorization_header` in stream configuration. I'm closing this issue, but feel free to reopen it if anything comes up.
